language: java
script:
#build the javadocs as part of the tests
  gradle javadoc
cache:
  directories:
  - $HOME/.m2

jdk:
  - oraclejdk8

# for running tests on Travis CI container infrastructure for faster builds
sudo: false
