language: java
before_script: compileJava jar
script: javadoc test 
cache:
  directories:
  - $HOME/.m2

jdk:
  - oraclejdk8

# for running tests on Travis CI container infrastructure for faster builds
sudo: false
